server:
  port: 8762

spring:
  application:
    name: eureka-client

eureka:
  instance:
    #访问路径可以显示IP地址
    prefer-ip-address: true
    instance-id: eureka-client8762
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
