server:
  port: 8763

spring:
  application:
    name: eureka-client

eureka:
  instance:
    #访问路径可以显示IP地址
    prefer-ip-address: true
      instance-id: eureka-client8763
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/